#!/usr/bin/env python3
"""
run_daily_scan.py - Daily job radar orchestrator

Orchestration order:
  1. Read config/target_companies.csv
  2. For each company, check career_url — mark manual_check_required if missing
  3. Fetch career pages (saves raw HTML to data/raw/)
  4. Parse jobs from raw data and data/raw/manual/
  5. Score jobs with keyword-based rules
  6. Deduplicate against data/seen_jobs.csv and data/rejected_jobs.csv
  7. Export exports/jobs_for_review.csv and exports/jobs_for_review.md
  8. Write exports/daily_summary.md
  9. Log everything to logs/daily_scan.log

Safe to run multiple times per day — idempotent by job_id.
Does NOT require Claude tokens.
Does NOT send applications.
Does NOT approve jobs.

Usage:
    python scripts/run_daily_scan.py [--dry-run] [--company "Company Name"]
    --dry-run    : Run through all logic but write no files
    --company    : Limit scan to one company (useful for debugging)
"""

import csv
import sys
import json
import logging
import argparse
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent
SCRIPTS_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPTS_DIR))

CONFIG_DIR = BASE_DIR / "config"
DATA_DIR = BASE_DIR / "data"
EXPORTS_DIR = BASE_DIR / "exports"
LOGS_DIR = BASE_DIR / "logs"
COMPANIES_CSV = CONFIG_DIR / "target_companies.csv"

LOGS_DIR.mkdir(parents=True, exist_ok=True)
EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

LOG_FILE = LOGS_DIR / "daily_scan.log"
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[logging.FileHandler(LOG_FILE), logging.StreamHandler()],
)
log = logging.getLogger(__name__)

import fetch_jobs
import parse_jobs
import score_jobs as score_jobs_module
import export_review_csv


def load_companies(company_filter: str | None = None) -> list:
    rows = []
    with open(COMPANIES_CSV, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            name = row["company_name"].strip()
            if company_filter and name.lower() != company_filter.lower():
                continue
            rows.append(row)
    return rows


def write_daily_summary(
    companies: list,
    fetch_results: list,
    scored_jobs: list,
    new_count: int,
    dry_run: bool,
):
    today = datetime.now().strftime("%Y-%m-%d %H:%M")
    total = len(companies)
    has_url = sum(1 for c in companies if c.get("career_url", "").strip())
    no_url = total - has_url

    fetched = sum(1 for r in fetch_results if r.get("status") == "fetched")
    failed = sum(1 for r in fetch_results if r.get("status") == "fetch_failed")
    manual_check = sum(1 for r in fetch_results if r.get("status") == "manual_check_required")

    high = [j for j in scored_jobs if int(j.get("fit_score") or 0) >= 8]
    med = [j for j in scored_jobs if 6 <= int(j.get("fit_score") or 0) <= 7]

    lines = [
        f"# Daily Scan Summary — {today}",
        "",
        f"{'[DRY RUN] ' if dry_run else ''}",
        "## Companies",
        f"- Total target companies: {total}",
        f"- With career URL: {has_url}",
        f"- Missing career URL (manual check needed): {no_url}",
        "",
        "## Fetch Results",
        f"- Pages fetched successfully: {fetched}",
        f"- Fetch failures: {failed}",
        f"- Manual check required (no URL): {manual_check}",
        "",
        "## Jobs Found This Run",
        f"- Total jobs parsed: {len(scored_jobs)}",
        f"- New jobs added to review: {new_count}",
        f"- High fit (score 8–10): {len(high)}",
        f"- Good fit (score 6–7): {len(med)}",
        "",
    ]

    if high:
        lines.append("## High-Fit Jobs (score ≥ 8)")
        for j in sorted(high, key=lambda x: -int(x.get("fit_score") or 0)):
            lines.append(f"- [{j.get('fit_score')}/10] **{j['company_name']}** — {j['role_title']}")
        lines.append("")

    companies_no_url = [c["company_name"] for c in companies if not c.get("career_url", "").strip()]
    if companies_no_url:
        lines.append("## Action Required — Missing Career URLs")
        lines.append("Edit `config/target_companies.csv` and add the career_url for:")
        for name in companies_no_url:
            lines.append(f"- {name}")
        lines.append("")

    lines.append("## Next Steps")
    lines.append("1. Review `exports/jobs_for_review.csv`")
    lines.append("2. Mark `approved_for_cv=yes` for roles you want to pursue")
    lines.append("3. Run: `python scripts/prepare_approved_jobs.py`")
    lines.append("")
    lines.append(f"_Generated by run_daily_scan.py at {today}_")

    out = EXPORTS_DIR / "daily_summary.md"
    if not dry_run:
        out.write_text("\n".join(lines), encoding="utf-8")
        log.info(f"Written → {out.relative_to(BASE_DIR)}")
    else:
        log.info("[DRY RUN] daily_summary.md not written")


def run(company_filter: str | None = None, dry_run: bool = False):
    start = datetime.now()
    log.info("=" * 60)
    log.info(f"Daily scan started — {start.strftime('%Y-%m-%d %H:%M:%S')}")
    if dry_run:
        log.info("[DRY RUN MODE] — no files will be written")
    if company_filter:
        log.info(f"Company filter: {company_filter}")

    # Step 1: Load companies
    companies = load_companies(company_filter)
    log.info(f"Loaded {len(companies)} companies from target_companies.csv")

    # Step 2 + 3: Fetch career pages
    log.info("--- FETCH ---")
    fetch_results = fetch_jobs.run(company_filter=company_filter, dry_run=dry_run)

    # Step 4: Parse jobs (manual + HTML)
    log.info("--- PARSE ---")
    parsed = parse_jobs.run(dry_run=dry_run)

    if not parsed:
        log.info("No jobs parsed this run.")
        log.info("Tip: add manual job files to data/raw/manual/ or populate career URLs.")
        write_daily_summary(companies, fetch_results, [], 0, dry_run)
        return

    # Step 5: Score jobs
    log.info("--- SCORE ---")
    scored = score_jobs_module.run(parsed, dry_run=dry_run)

    # Step 6 + 7: Export review files
    log.info("--- EXPORT ---")
    new_count = export_review_csv.run(scored_jobs=scored, dry_run=dry_run)

    # Step 8: Write daily summary
    log.info("--- SUMMARY ---")
    write_daily_summary(companies, fetch_results, scored, new_count, dry_run)

    elapsed = (datetime.now() - start).total_seconds()
    log.info(f"Daily scan complete — {elapsed:.1f}s — {new_count} new jobs added to review")
    log.info("=" * 60)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run daily job radar scan")
    parser.add_argument("--dry-run", action="store_true",
                        help="Run through all logic but write no files")
    parser.add_argument("--company", help="Limit scan to a specific company name")
    args = parser.parse_args()
    run(company_filter=args.company, dry_run=args.dry_run)
